"""add stored_path to knowledge_documents

Revision ID: 83c120e58cfa
Revises: 063c28ca7a0d
Create Date: 2026-10-01 15:41:51.165580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '83c120e58cfa'
down_revision: Union[str, None] = '063c28ca7a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stored_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_column('stored_path')

    # ### end Alembic commands ###
